### ISSUE TITLE
Can't sell items in picking phase anymore

### ISSUE THREAD

**Issue by hipunk** [dota2unofficial/12v12#10]
Usually you can buy items in the picking phase and resell them by right clicking them in your inventory again. That doesn't work at the moment, but it did in one of your recent, but now also older, versions.

**Comment by quantuumsnot** [comment]
+1

In a good number of matches starting builds are broken due to unsellable items during pick phase, especially when the user faces the notorious 'missing RANDOM seconds from reality' lag-bug. Even if he managed to pick his preferred hero, there's a chance for misclicking on item or the worse - receiving gold penalty during pick phase because this lag-bug time-teleported to 0 remaining seconds ...

**Comment by darklordabc** [comment]
I could sell
