### ISSUE TITLE
Add Text to Silencer Informing Player he doesnt steal int

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#6]
Removed his ability to steal int here, perhaps not the best possible nerf, may be addressed later in a better fashion. Need to add text to his hero name saying "MODIFIED" and text to glaives indicating he does not steal int. 

https://github.com/darklordabc/12v12/commit/f30bee00453a94109420d199cb4733d226829969

**Comment by EarthSalamander42** [comment]
Stealing 1 int per kills is still too much?

**Comment by darklordabc** [comment]
He steals two int by default and 2 more with his talent, I see no way to override his default 2 int steal.

**Comment by EarthSalamander42** [comment]
Well i can add luafied version of the ability tomorrow, and give you the ability to control it (for the talent i'd suggest just replacing it with a generic one)

**Comment by laiprorus** [comment]
slark does still agility now too, 1 point for anyone dying with his attribute debuff active

**Comment by ZackNovazich** [comment]
Ban Silencer,PLZ!!!!!!!!

**Comment by darklordabc** [comment]
Why Zack? He doesnt steal INT anymorme, how is he broken? Because he can silence you for 4 seconds?

**Comment by ZackNovazich** [comment]
PLZ show that someone quit the game, if u just disappear it that's not obvious.sometimes i didn't know some of my teamates has quit the game!!!!!

**Comment by darklordabc** [comment]
Cant you see this ingame update log 
![image](https://user-images.githubusercontent.com/16277198/49391603-09cb4580-f724-11e8-9bf3-242c2fca6470.png)

**Comment by adminnz** [comment]
Why remove the ability for silencer to steal int? 
If Silencer cant steal int, why is Slark still allowed to steal agility?

If its more about snowballing then why is Pudge allowed to gain strength?
What about Legion Commander with damage (it is not uncommon for a LC to have +500 damage or more) ?

If its because he just needs to be in an area to get int, then why not make it so Glaives apply a magic piercing debuff  (to avoid issues with bkb) to heroes and if the hero dies with the debuff then Silencer gains +2 int ?

**Comment by darklordabc** [comment]
He does steal int now
