### ISSUE TITLE
The Game crashes ever 29th minute.... everyone cant reconnect again.

### ISSUE THREAD

**Issue by riri323** [dota2unofficial/12v12#61]

**Comment by darklordabc** [comment]
What. 29 minutes into the game it crashes, consistently?

**Comment by GeneralDotV2** [comment]
Something doesn't sound right about that.

**Comment by riri323** [comment]
For 3 games in a row now. I asked people from the lobby and they had the same thing. 28th or 29th minute. It disconnects everyone and womt let us Recon. 


But they said this also happened to other arcade games.

**Comment by GeneralDotV2** [comment]
Must be something Valve messed up then. I'll test on my own to see if the same thing happens to me.

**Comment by GeneralDotV2** [comment]
Can you send me the match ID of one of the games that crashed for you?

**Comment by GeneralDotV2** [comment]
An update on this issue. Turns out Monkey King was causing server crashes when reverting the mischief form ability. As can be seen here.
https://cdn.win-serv.com/ShareX/GeneralDotV2/09-26-2019/generaldotv2_Thu09-26-2019_18-26-04.15_monkey_king_crash_mischief.mp4

This issue has now been fixed in the most recent update.

**Comment by darklordabc** [comment]
I think this may be fixed, please close the issue if it is

**Comment by fcalife** [comment]
@darklordabc fixed by valve yesterday

**Comment by darklordabc** [comment]
Awesome
